name: 'Ziplo - Github Action'
description: 'This action help you to protect your source code with Ziplo'
branding:
  icon: 'shield'
  color: 'purple'
inputs:
  organization-token:
    description: 'Your organization token'
    required: true
    default: null
  project-token:
    description: 'Your consignment project token'
    required: true
    default: null
  version:
    description: 'Version of your source code'
    required: false
    default: null
  filepath:
    description: 'File path of your source code'
    required: false
    default: null
runs:
  using: 'node16'
  main: 'index.js'
